// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqS4I4c5Eseqxq8TbUJ1Cq6KmZGRlbZQ',
    appId: '1:341311946960:web:8c7e1ffb9ef14d82681ed5',
    messagingSenderId: '341311946960',
    projectId: 'cellua-22713',
    authDomain: 'cellua-22713.firebaseapp.com',
    storageBucket: 'cellua-22713.appspot.com',
    measurementId: 'G-T4LSPQ1BYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB72iQQ97tWzDy0ghReW6o4ZtOb-TYKffw',
    appId: '1:341311946960:android:fbdb2520cdabd4c7681ed5',
    messagingSenderId: '341311946960',
    projectId: 'cellua-22713',
    storageBucket: 'cellua-22713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0RxJxlSjkOyPg10W38TC-373LzsR-2Nw',
    appId: '1:341311946960:ios:1ee29a2819e49350681ed5',
    messagingSenderId: '341311946960',
    projectId: 'cellua-22713',
    storageBucket: 'cellua-22713.appspot.com',
    iosBundleId: 'com.example.aiTennis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0RxJxlSjkOyPg10W38TC-373LzsR-2Nw',
    appId: '1:341311946960:ios:1ee29a2819e49350681ed5',
    messagingSenderId: '341311946960',
    projectId: 'cellua-22713',
    storageBucket: 'cellua-22713.appspot.com',
    iosBundleId: 'com.example.aiTennis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkqS4I4c5Eseqxq8TbUJ1Cq6KmZGRlbZQ',
    appId: '1:341311946960:web:66d1fadbdc659c3c681ed5',
    messagingSenderId: '341311946960',
    projectId: 'cellua-22713',
    authDomain: 'cellua-22713.firebaseapp.com',
    storageBucket: 'cellua-22713.appspot.com',
    measurementId: 'G-EX8VW4SFRQ',
  );
}
